### PR TITLE
Add simple test

### PR DESCRIPTION
**Pull request by fredrikaverpil**
This will just add _something_ to test.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
Whaaaat the... all of a sudden, all CI builds are running on Windows. Something must be wrong in Azure...?

**Comment by fredrikaverpil** [comment]
If I edit the host to run the pipeline in Azure (from "Hosted" to "macOS") ... it seems to work for macOS now. But this value of "Hosted" has worked all the time and the `vmImage` key has been picked up properly.

**Comment by fredrikaverpil** [comment]
Hmmm ... let's see if the vmImage key is still not respected...

**Comment by fredrikaverpil** [comment]
For some reason, the "Hosted" pool does no longer work, it seems. I am now setting specifically ubuntu for the ubuntu pipeline and macOS for the macOS pipeline.

**Comment by fredrikaverpil** [comment]
Bah... I wonder if MS is updating the Python versions, as now 3.6.4 is no longer available on the Windows platform.

**Comment by fredrikaverpil** [comment]
I just realized... it's just on Windows that python3 is installed by vcpkg?

And ... the error persists: https://fredrikaverpil.visualstudio.com/oiio-python/_build/results?buildId=744&view=logs&jobId=71d407c9-c576-569c-7d43-abe3f2f427cf&taskId=ed664dd9-9b0e-5ab2-10a8-5fd608a7bd12&lineStart=29&lineEnd=33&colStart=1&colEnd=1

**Comment by SidneyGuenther** [comment]
@fredrikaverpil Even if the CONTROL file of pybind11 on mac and linux isn't listing the python3 package as a dependency, it has to be installed though.

**Pull request merged**
